# Generated by Django 5.2.15 on 2026-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('energy', 'Энергетика (нефть, газ, уголь)'), ('mining', 'Добывающая промышленность и металлургия'), ('utilities', 'Коммунальные услуги (Utilities)'), ('manufacturing', 'Промышленное производство'), ('construction', 'Строительство и недвижимость'), ('transport', 'Транспорт и логистика'), ('financial', 'Финансовые услуги'), ('tech', 'Технологии и ПО'), ('telecom', 'Телекоммуникации и медиа'), ('retail', 'Ритейл и товары народного потребления'), ('healthcare', 'Здравоохранение и фармацевтика'), ('agriculture', 'Сельское хозяйство и производство продуктов питания'), ('services', 'Профессиональные услуги / образование / консалтинг'), ('other', 'Прочее')], max_length=30),
        ),
    ]
