services:
  db:
    image: postgres:16-alpine
    container_name: esg_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: esg_db
      POSTGRES_USER: esg_user
      POSTGRES_PASSWORD: esg_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esg_user -d esg_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: