# Generated by Django 5.2.15 on 2026-06-26 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('INDUSTRY', 'Промышленность'), ('EDUCATION', 'Образование'), ('MINING', 'Добыча'), ('OTHER', 'Другое')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('block', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Да/Нет'), ('single_choice', 'Один вариант'), ('scale', 'Шкала')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('level', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_e', models.FloatField()),
                ('score_s', models.FloatField()),
                ('score_g', models.FloatField()),
                ('score_total', models.FloatField()),
                ('level', models.CharField(choices=[('BEGINNER', 'Начальный'), ('DEVELOPING', 'Развивающийся'), ('ADVANCED', 'Продвинутый'), ('LEADER', 'Лидер')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment.company')),
            ],
        ),
    ]
