# Generated by Django 6.0.6 on 2026-07-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=20, unique=True)),
                ('is_controversy', models.BooleanField(default=False)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('block', models.CharField(blank=True, choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1, null=True)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('single_choice', 'Single choice'), ('scale', 'Scale'), ('percentage', 'Percentage')], max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('level', models.CharField(max_length=32)),
                ('text_ru', models.TextField()),
                ('text_kz', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['block', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_e', models.FloatField(default=0)),
                ('score_s', models.FloatField(default=0)),
                ('score_g', models.FloatField(default=0)),
                ('score_total', models.FloatField(default=0)),
                ('level', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.result')),
            ],
        ),
    ]
