# Generated by Django 5.2.15 on 2026-07-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('block', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('single_choice', 'Single Choice'), ('scale', 'Scale')], max_length=20)),
                ('weight', models.FloatField(default=1)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('advanced', 'Advanced'), ('leader', 'Leader')], max_length=20)),
                ('text_ru', models.TextField()),
                ('text_kz', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_e', models.FloatField()),
                ('score_s', models.FloatField()),
                ('score_g', models.FloatField()),
                ('score_total', models.FloatField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('advanced', 'Advanced'), ('leader', 'Leader')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.result')),
            ],
        ),
    ]
