# Generated by Django 5.2.15 on 2026-07-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('single_choice', 'Single choice'), ('scale', 'Scale'), ('percent', 'Percent')], max_length=32),
        ),
    ]
