# Generated by Django 5.2.15 on 2026-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('single_choice', 'Single choice'), ('scale', 'Scale'), ('percentage', 'Percentage')], max_length=32),
        ),
    ]
